import { describe, it, expect } from 'vitest';
import { readFileSync, readdirSync, existsSync } from 'node:fs';
import { join } from 'node:path';
import { Midi } from '../../src/midi/Midi.js';
import { messageBytes } from '../../src/midi/MidiTypes.js';

/**
 * The SMF writer, against Java-generated bytes.
 *
 * `midi-byte-equivalence.test.ts` never reaches the writer: `Msm.exportMidi` returns a `Midi`
 * object, so `Midi.exportMidi` and `buildTrackChunk` are never called on that path — measured
 * by making every meta payload declare a length of zero and watching all 43 of those tests
 * pass. The writer's only other coverage is an export-then-re-read round trip in
 * `tests/midi/Midi.test.ts`, which checks self-consistency rather than agreement with anything
 * external.
 *
 * The property asserted here is the one `src/midi/Midi.ts`'s header states: read a Java `.mid`
 * through `readMidiData`, write it back through `exportMidi`, and most of the corpus comes out
 * byte-identical. Measured: 33 of the 48 references are identical, 14 are longer, one shorter.
 *
 * Every file is required to be byte-identical unless it is named in {@link KNOWN_DELTAS}, so a
 * new fixture is held to the strict standard by default and an existing exception cannot
 * change size unnoticed. The exceptions have two documented causes, neither a defect:
 *
 * - Running status. The JDK's writer compresses consecutive same-status channel messages; this
 *   one always emits the full status byte. The reader understands running status on input,
 *   which is why the event streams still agree. That accounts for all 14 longer files. (The
 *   `Midi.ts` header says "2-3 bytes longer", which is wrong and is corrected there: the real
 *   range is +1 to +13, and it scales with how much the JDK managed to compress.)
 * - A negative tick. `ornamentation_expressive.mid` genuinely begins at tick −18 — the
 *   ornamentation renderer can move an event before the start — which the JDK wrote as a
 *   10-byte VLQ. This reader recovers −18 exactly through its 32-bit wraparound and the writer
 *   then clamps the delta to 0, which is 2 bytes shorter. It is the one reference whose event
 *   stream is not a fixed point of read-then-write, and the only negative entry below.
 */

const DIRS = [
  join(import.meta.dirname, 'fixtures', 'performance-reference'),
  join(import.meta.dirname, 'fixtures', 'all-maps-reference'),
];

/**
 * The only permitted departures from byte-identity, as exact size deltas.
 *
 * A file absent from this table must re-export byte for byte. Measured on the committed tree;
 * if one of these numbers moves, the writer changed and the change needs an explanation.
 */
const KNOWN_DELTAS: Readonly<Record<string, number>> = {
  // Running status the JDK used and this writer re-expands.
  'composite_advanced_expressive.mid': 3,
  'composite_advanced_raw.mid': 3,
  'comprehensive_expressive.mid': 2,
  'comprehensive_raw.mid': 2,
  'instruments_expressive.mid': 1,
  'instruments_raw.mid': 1,
  'layers_beams_expressive.mid': 8,
  'layers_beams_raw.mid': 8,
  'ties_dots_expressive.mid': 1,
  'ties_dots_raw.mid': 1,
  'all_maps_expressive.mid': 1,
  'imprecision_timing_expressive.mid': 3,
  'movement_expressive.mid': 13,
  'ornamentation_raw.mid': 8,
  // The negative first tick, clamped to 0 on write.
  'ornamentation_expressive.mid': -2,
};

interface Reference {
  readonly name: string;
  readonly bytes: Uint8Array;
}

function loadReferences(): readonly Reference[] {
  const out: Reference[] = [];
  for (const dir of DIRS) {
    if (!existsSync(dir)) continue;
    for (const file of readdirSync(dir).sort()) {
      if (!file.endsWith('.mid')) continue;
      out.push({ name: file, bytes: new Uint8Array(readFileSync(join(dir, file))) });
    }
  }
  return out;
}

const REFERENCES = loadReferences();

/** Every event in the file, flattened across tracks, as `tick:byte,byte,…`. */
function eventStream(bytes: Uint8Array): readonly string[] {
  const out: string[] = [];
  for (const track of Midi.fromBytes(bytes).getSequence().getTracks()) {
    for (let i = 0; i < track.size(); ++i) {
      const event = track.get(i);
      out.push(`${String(event.getTick())}:${[...messageBytes(event.getMessage())].join(',')}`);
    }
  }
  return out;
}

function reExport(bytes: Uint8Array): Uint8Array {
  // `exportMidi` returns null for an empty document. None of the references is empty, so a
  // null here means the reader silently produced nothing — asserted rather than defaulted.
  const out = Midi.fromBytes(bytes).exportMidi();
  expect(out).not.toBeNull();
  return out as Uint8Array;
}

describe('SMF writer against the Java references', () => {
  it('auto-discovers the whole corpus, so a new reference is covered without editing this file', () => {
    expect(REFERENCES.length).toBe(48);
  });

  it('names no exception that is not in the corpus', () => {
    // Guards the table against rot: a renamed or deleted fixture must not leave a stale
    // licence behind that would silently excuse a different file later.
    const present = new Set(REFERENCES.map((r) => r.name));
    for (const name of Object.keys(KNOWN_DELTAS)) expect(present).toContain(name);
  });

  it('holds 33 of the 48 to exact byte identity', () => {
    // The headline number, asserted so that quietly moving a file into KNOWN_DELTAS to make a
    // failure go away shows up as a second failure here.
    expect(REFERENCES.length - Object.keys(KNOWN_DELTAS).length).toBe(33);
  });

  describe.each(REFERENCES)('$name', ({ name, bytes }) => {
    const expectedDelta = KNOWN_DELTAS[name] ?? 0;

    it('re-exports at exactly the documented size', () => {
      expect(reExport(bytes).length - bytes.length).toBe(expectedDelta);
    });

    if (expectedDelta === 0) {
      it('re-exports byte for byte', () => {
        expect([...reExport(bytes)]).toEqual([...bytes]);
      });
    }

    it('is a fixed point from the second write on', () => {
      // Whatever the first write does to running status, doing it again must change nothing —
      // otherwise the writer is not a function of the event stream.
      const once = reExport(bytes);
      expect([...reExport(once)]).toEqual([...once]);
    });

    it('preserves the event stream', () => {
      // The invariant the size deltas are allowed to violate and this one is not: re-encoding
      // may spend more bytes, but it may not change a single event.
      const before = eventStream(bytes);
      const after = eventStream(reExport(bytes));
      if (name === 'ornamentation_expressive.mid') {
        // `Midi.ts`'s header says the writer "clamps the negative delta to 0 on export",
        // which sounds local and is not: deltas are computed from absolute ticks, so turning
        // this track's first event from -18 into 0 leaves every later delta unchanged and
        // therefore moves every later event 18 ticks further from the start. Measured: track
        // 0 (2 events, starting at 0) is untouched; all 43 events of track 1 shift by exactly
        // +18. The track is re-anchored, not re-encoded — not one message byte changes.
        const tickOf = (e: string): number => Number(e.slice(0, e.indexOf(':')));
        const payloadOf = (e: string): string => e.slice(e.indexOf(':') + 1);

        expect(after.length).toBe(before.length);
        expect(Math.min(...before.map(tickOf))).toBe(-18);
        expect(Math.min(...after.map(tickOf))).toBe(0);
        expect([...new Set(after.map((e, i) => tickOf(e) - tickOf(before[i])))].sort()).toEqual([
          0, 18,
        ]);
        expect(after.map(payloadOf)).toEqual(before.map(payloadOf));
      } else {
        expect(after).toEqual(before);
      }
    });
  });
});
